config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :image_mappers
    resources :banners do
      collection do
        get :search
        get :search_paginate
      end
    	member do
          get :pin
      end
      end
  end
end

app/models/spree/banner.rb
module Spree
  class Banner < ActiveRecord::Base
    attr_accessible :name, :url, :image_name, :sale_event_id, :banner_type, :position, :live , :target
    
    belongs_to :active_sale_event, :class_name => "Spree::ActiveSaleEvent", :foreign_key => "sale_event_id"

    validates :position, :image_name, :banner_type, :presence => true
    has_many :image_mappers
    
    scope :live_banners, lambda {|tag, type | where("live = :live and name = :name and banner_type = :banner_type", {:live => true, :name => tag, :banner_type => type }) } 
    TYPES = %w(Head Side Menu)
    
    def image_url
      "http://slider.styletagassets.com/banners/#{self.image_name}"
    end
    
    def sale_path
      self.url.blank? ? self.active_sale_event.permalink : self.url 
    end
    
  end
end

app/controllers/spree/admin/banners_controller.rb
module Spree
  module Admin
    class BannersController < ResourceController

      #before_filter :is_cs
      before_filter :load_menus#, :only => [:new, :edit, :create, :update]

      # GET /banners
      # GET /banners.xml
      def index
        @banners = Spree::Banner.order('updated_at desc').where(:live => true ).page(params[:page]).per(30)
        #@banners = Banner.order(:live).reverse#.reverse.sort_by { |banner| banner.position }.paginate(:page => params[:page], :per_page => 30)

        respond_to do |format|
          format.html # index.html.erb
          format.xml  { render :xml => @banners }
        end
      end

      # GET /banners/1
      # GET /banners/1.xml
      def show
        @banner = Banner.find(params[:id])

        respond_to do |format|
          format.html # show.html.erb
          format.xml  { render :xml => @banner }
        end
      end

      # GET /banners/new
      # GET /banners/new.xml
      def new
        @banner = Banner.new
        @types = Banner::TYPES

        respond_to do |format|
          format.html # new.html.erb
          format.xml  { render :xml => @banner }
        end
      end

      # GET /banners/1/edit
      def edit
        @banner = Banner.find(params[:id])
        @types = Banner::TYPES
      end

      # POST /banners
      # POST /banners.xml
      def create
        params["banner"]["sale_event_id"] = nil if params["banner"]["sale_event_id"] == ""
        @banner = Banner.new(params[:banner])
        @types = Banner::TYPES

        respond_to do |format|
          if @banner.save
            format.html { redirect_to(admin_banners_path, :notice => 'Banner was successfully created.') }
            format.xml  { render :xml => @banner, :status => :created, :location => @banner }
          else
            format.html { render :action => "new" }
            format.xml  { render :xml => @banner.errors, :status => :unprocessable_entity }
          end
        end
      end

      # PUT /banners/1
      # PUT /banners/1.xml
      def update
        params["banner"]["sale_event_id"] = nil if params["banner"]["sale_event_id"] == ""
        @banner = Banner.find(params[:id])
        @types = Banner::TYPES

        respond_to do |format|
          if @banner.update_attributes(params[:banner])
            format.html { redirect_to(admin_banners_path, :notice => 'Banner was successfully updated.') }
            format.xml  { head :ok }
          else
            format.html { render :action => "edit" }
            format.xml  { render :xml => @banner.errors, :status => :unprocessable_entity }
          end
        end
      end

      # DELETE /banners/1
      # DELETE /banners/1.xml
      def destroy
        @banner = Banner.find(params[:id])
        @banner.destroy

        respond_to do |format|
          format.html { redirect_to(admin_banners_url) }
          format.xml  { head :ok }
        end
      end

      def pin
        @banner = Banner.find(params[:id])
        @pins=@banner.image_mappers
        #render :json => @banner 
      end  

      def load_menus
        @active_sale_ids = Spree::ActiveSaleEvent.live_active.sort_by { |as| as.eventable.name.upcase }
        #@all_sales_menu = (Spree::ActiveSaleEvent.live_active.roots.map{|ss| ss.name} << ["marketing", "lookbook", "newin", "designer"]).flatten
        cats = [["Home", "marketing"]]
        Spree::ActiveSaleEvent.live_active.roots.each{|cat1|  cats << [cat1.name.humanize, cat1.permalink] unless cat1.permalink == "t/designers"}
        Spree::ActiveSaleEvent.live_active.roots.each{|cat1| cat1.descendants.live.each{|cat2| cats << [cat2.permalink.gsub("t/designers/", ""), cat2.permalink]}}
        Spree::ActiveSaleEvent.live_active.roots.each{|cat1| cat1.descendants.live.each{|cat2| cat2.descendants.live.each{|cat3| cats << [cat3.permalink.gsub("t/designers/", ""), cat3.permalink]}}}
        @all_sales_menu = cats
      end

      def search
        if params[:filter].eql? 'All'
          name_ids = Spree::ActiveSaleEvent.where("name like ?", "%#{params[:search]}%").collect(&:id) rescue []
          url_ids = Spree::ActiveSaleEvent.where("permalink like ?", "%#{params[:search]}%").collect(&:id) rescue []
          url_link = Spree::Banner.where("url like ? or name like ?", "%#{params[:search]}%", "%#{params[:search]}%").collect(&:id) rescue []
          ids =  name_ids + url_ids
          @banners =  Spree::Banner.where('sale_event_id IN(?) OR id IN(?)', ids, url_link).page(params[:page]).per(30)
        end

        if params[:filter].eql? 'Active'
          name_ids = Spree::ActiveSaleEvent.where("name like ?", "%#{params[:search]}%").collect(&:id)  rescue []
          url_ids = Spree::ActiveSaleEvent.where("permalink like ?", "%#{params[:search]}%").collect(&:id) rescue []
          url_link = Spree::Banner.where("url like ? or name like ?", "%#{params[:search]}%", "%#{params[:search]}%").collect(&:id) rescue []
          ids =  name_ids + url_ids
          @banners =  Spree::Banner.where(:live => true ).where('sale_event_id IN(?) OR id IN(?)', ids, url_link).page(params[:page]).per(30)
        end

        if params[:filter].eql? 'In-Active'
          name_ids = Spree::ActiveSaleEvent.where("name like ?", "%#{params[:search]}%").collect(&:id) rescue []
          url_ids = Spree::ActiveSaleEvent.where("permalink like ?", "%#{params[:search]}%").collect(&:id) rescue []
          url_link = Spree::Banner.where("url like ? or name like ?", "%#{params[:search]}%", "%#{params[:search]}%").collect(&:id) rescue []
          ids =  name_ids + url_ids
          @banners =  Spree::Banner.where(:live => false ).where('sale_event_id IN(?) OR id IN(?)', ids, url_link).page(params[:page]).per(30)
        end

        render :partial => 'spree/admin/banners/search_banners'
      end

      def search_paginate

        if params[:filter].eql? 'All'
          name_ids = Spree::ActiveSaleEvent.where("name like ?", "%#{params[:search]}%").collect(&:id)  rescue []
          url_ids = Spree::ActiveSaleEvent.where("permalink like ?", "%#{params[:search]}%").collect(&:id) rescue []
          url_link = Spree::Banner.where("url like ?", "%#{params[:search]}%").collect(&:id) rescue []
          ids =  name_ids + url_ids
          @banners =  Spree::Banner.where('sale_event_id IN(?) OR id IN(?)', ids, url_link).page(params[:page]).per(30)
        end

        if params[:filter].eql? 'Active'
          name_ids = Spree::ActiveSaleEvent.where("name like ?", "%#{params[:search]}%").collect(&:id)  rescue []
          url_ids = Spree::ActiveSaleEvent.where("permalink like ?", "%#{params[:search]}%").collect(&:id) rescue []
          url_link = Spree::Banner.where("url like ?", "%#{params[:search]}%").collect(&:id) rescue []
          ids =  name_ids + url_ids
          @banners =  Spree::Banner.where(:live => true ).where('sale_event_id IN(?) OR id IN(?)', ids, url_link).page(params[:page]).per(30)
        end

        if params[:filter].eql? 'In-Active'
          name_ids = Spree::ActiveSaleEvent.where("name like ?", "%#{params[:search]}%").collect(&:id)  rescue []
          url_ids = Spree::ActiveSaleEvent.where("permalink like ?", "%#{params[:search]}%").collect(&:id)  rescue []
          url_link = Spree::Banner.where("url like ?", "%#{params[:search]}%").collect(&:id) rescue []
          ids =  name_ids + url_ids
          @banners =  Spree::Banner.where(:live => false ).where('sale_event_id IN(?) OR id IN(?)', ids, url_link).page(params[:page]).per(30)
       end

      end

    end
  end
end

app/views/spree/admin/banners/_form.html.erb
<%= form_for([:admin,@banner], :html => { :class => "form-horizontal" }) do |f| %>
  <% if @banner.errors.any? %>
    <div id="error_explanation" class="alert alert-error">
      <h2><%= pluralize(@banner.errors.count, "error") %> prohibited this banner from being saved:</h2>
      <ul>
        <% @banner.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <div class="control-group">
      <div class="field eight columns" style="margin-left: 0px;">
         <label for="menu_name" style="font-size: 12px;">
          <%= f.label :menu_name %>
         </label>
          <%= select_tag "banner[name]", options_for_select(@all_sales_menu, @banner.name), {:class => 'select2 select_item_total fullwidth'} %>
        </div>
      </label>
    </div>
  </p>
   <div style="clear:both; float:none;"></div> 
  <div class="control-group">
    <%= f.label :url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :url %> Full URL where you want a user to go.
    </div>
  </div>
  <div class="control-group">
    <%= f.label :image_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :image_name %> Strictly to be same as image's name.
    </div>
  </div>
  <p>
  <div style="clear:both; float:none;"></div>
  <div class="control-group">
    
    <div class="field alpha four columns">
      <label for="sale" style="font-size: 12px;" >
        <%= f.label :sale %>
      </label>
      <%= select_tag "banner[sale_event_id]", options_for_select(@active_sale_ids.map { |sale| [sale.eventable.name.humanize, sale.id] } << ["No Sales", nil], :selected => (@banner.sale_event_id.nil? ?  ["No Sales", nil] : @banner.sale_event_id) ), {:class => 'select2 select_item_total fullwidth'} %>
    </div>
  </div>
  </p>
  <div style="clear:both; float:none;"></div>
  <div class="control-group">
    <%= f.label :banner_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :banner_type, @types.map { |type| [type.humanize, type] }, { :prompt => "Please select a type" }, { :class => "span3"} %> Must be selected!
    </div>
  </div>
  <div style="clear:both; float:none;"></div>
  <div class="control-group">
    <%= f.label :position, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :position, :class => "span1" %> Must be given! Can be 0, 1, 99 or any integer!
    </div>
  </div>
  <div style="clear:both; float:none;"></div>
  <div class="control-group">
    <%= f.label :live, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :live %>
    </div>

    <div class="controls">
      <%= f.label :target, '_target_blank' %>
      <%= f.check_box :target %>
    </div>

  </div>
  <div style="clear:both; float:none;"></div>
  <div class="form-actions">
    <%= f.submit(:class => "btn btn-primary" ) %>
  </div>
<% end %>

app/views/spree/admin/banners/_list_pins.html.erb
<div id="image_pins">
<h1>Listing Image Pins</h1>

<table class="table table-striped table-bordered table-condensed" >
  <thead>
    <tr>
      <th>X1</th>
      <th>Y1</th>
      <th>X2</th>
      <th>Y2</th>
      <th>Image Link</th>
      <th>Image Alt</th>
      <th>Shape</th>
      <th>Target blank</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @pins && @pins.each do |pin| %>
      <tr>
        <td><%= pin.x1 %></td>
        <td><%= pin.y1 %></td>
        <td><%= pin.x2 %></td>
        <td><%= pin.y2%></td>
        <td><%= pin.link %></td>
        <td><%= pin.alt %></td>
        <td><%= pin.shape %></td>
        <td><%= pin.target %></td>
        <td><%= link_to 'Show', "#" %></td>
        <td><%= link_to 'Edit', "#" %></td>
        <td><%= link_to 'Destroy', "#", :confirm => 'Are you sure?', :method => :delete %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br />
</div>

app/views/spree/admin/banners/_pins_area.html.erb
<div id="pins_in_image">
<% @pins && @pins.each do |p|%>
            <area id="<%=p.id%>" shape="<%=p.shape%>" coords="<%=p.x1%>,<%=p.y1%>,<%=p.x2%>,<%=p.y2%>" href="javascript:void(0)" alt="<%=p.alt%>">
<%end%>
</div>

app/views/spree/admin/banners/_search_banners.html.erb
<%= paginate(@banners, :remote => true, :params => {:action => :search_paginate }) %>
<table class="table table-striped table-bordered table-condensed">
  <thead>
  <tr>
    <th>Menu Name</th>
    <th>URL</th>
    <th>Image</th>
    <th>Sale</th>
    <th>Is Live?</th>
    <th>Position</th>
    <th>Type</th>
    <th>target _blank</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @banners.each do |banner| %>
      <tr>
        <td>
          <% name = @all_sales_menu.select{ |name, permalink| banner.name == permalink}  %>
          <%= name.first.try(:first) %>
        </td>
        <td><%= banner.try(:url) %></td>
        <td><%= image_tag("http://slider.styletagassets.com/banners/#{banner.try(:image_name)}", :size => "125x30") %></td>
        <td><%= banner.try(:active_sale_event).try(:eventable).try(:name) %></td>
        <td><%= banner.live %></td>
        <td><%= banner.position %></td>
        <td><%= banner.banner_type %></td>
        <td><%= banner.target %></td>
        <td><%= link_to 'Pin', pin_admin_banner_path(banner) %></td>
        <td><%= link_to 'Show', admin_banner_path(banner) %></td>
        <td><%= link_to 'Edit', edit_admin_banner_path(banner) %></td>
        <td><%= link_to 'Destroy', admin_banner_path(banner), :confirm => 'Are you sure?', :method => :delete %></td>

      </tr>
  <% end %>
  </tbody>
</table>

<%= paginate(@banners, :remote => true, :params => {:action => :search_paginate }) %>

app/views/spree/admin/banners/edit.html.erb
<h1>Editing Banner</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_banner_path(@banner) %> |
<%= link_to 'Back', admin_banners_path %>

app/views/spree/admin/banners/index.html.erb
<% content_for :page_actions do %>
    <li>
      <%= button_link_to t(:new_banner), spree.new_admin_banner_path, :icon => 'icon-plus' %>
    </li>
<% end %>

<% unless @banners.any? %>
    <div class="no-objects-found">
      <%= t(:no_banners_found) %>
    </div>
<% else %>


    <%= form_tag "/admin/banners/search" , :remote => true, :id => 'search_banner', :dataType => 'html', :method => :get  do  %>
        <%= select_tag "filter", options_for_select(['All', 'Active', 'In-Active'], :selected => "Active"),  :class => 'type-select select2', :style => 'width: 100px;' %>
        <%= text_field_tag "search" , params[:search_taxons] , :placeholder =>  'search by banner', :style => 'width: 400px;' %>
        <%= button_tag 'search' , :id => 'ban_search_form' %>
    <% end %>


    <div style="padding:10px"></div>
    <div id="show_banners">

    </div>


<div id="all_ban">
  <%= paginate(@banners) %>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Menu Name</th>
      <th>URL</th>
      <th>Image</th>
      <th>Sale</th>
      <th>Is Live?</th>
      <th>Position</th>
      <th>Type</th>
      <th>target _blank</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @banners.each do |banner| %>
      <tr>
        <td>
          <% name = @all_sales_menu.select{ |name, permalink| banner.name == permalink}  %>
          <%= name.first.try(:first) %>
        </td>
        <td><%= banner.try(:url) %></td>
        <td><%= image_tag("http://slider.styletagassets.com/banners/#{banner.try(:image_name)}", :size => "125x30") %></td>
        <td><%= banner.try(:active_sale_event).try(:eventable).try(:name) %></td>
        <td><%= banner.live %></td>
        <td><%= banner.position %></td>
        <td><%= banner.banner_type %></td>
        <td><%= banner.target %></td>
        <td><%= link_to 'Pin', pin_admin_banner_path(banner) %></td>
        <td><%= link_to 'Show', admin_banner_path(banner) %></td>
        <td><%= link_to 'Edit', edit_admin_banner_path(banner) %></td>
        <td><%= link_to 'Destroy', admin_banner_path(banner), :confirm => 'Are you sure?', :method => :delete %></td>

      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @banners %>
</div>
<% end %>

<script type="text/javascript">

    $(document).ready(function(){
        $('form#search_banner').on('ajax:success',function(event, data, status, xhr){
            $('#all_ban').hide();
            $('#show_banners').html(data);
        });
    });

</script>

app/views/spree/admin/banners/new.html.erb
<h1>New Banner</h1>

<%= render 'form' %>

<%#= link_to 'Back', banners_path %>

app/views/spree/admin/banners/pin.html.erb
<style type="text/css">
.container {
        margin: 0 !important;
}
#edit_map
{
background-color: black;
position:fixed;
top:30px;
right:5px;
width: 180px;
}
.close_map_form{
       color: red;
       margin: 5px;
       float: right;
}
#close_map_form a{
       color: red;
}

</style>
<%=image_tag @banner.image_url, :alt=> @banner.name, :usemap => "#shelfmap",:id => "bn_image" %>
<map name="shelfmap">
<%= render :partial => 'spree/admin/banners/pins_area' %>
</map>
<%= form_tag "/admin/image_mappers", :method => :post,:remote=>true do %>
X1 <%=text_field_tag :x1 %>
Y1<%=text_field_tag :y1 %>
X2<%=text_field_tag :x2 %>
Y2<%=text_field_tag :y2 %>
link<%=text_field_tag :link %>
Alt<%=text_field_tag :alt %>
Shape<%=text_field_tag :shape %>
_target_blank
<%= check_box_tag :target %>

<%=hidden_field_tag :id,params[:id]%>
<section  class="span11">
<%= submit_tag 'Create', :id => 'image_mapper_create', :class=> 'btn pull-right '%>
</section>
<%end%>


<div id="edit_map" style="display:none">
<span class="close_map_form"><a href="javascript:void(0)">X</a></span>
X1<input type="text" id="x1" />
Y1<input type="text" id="y1" />
X2<input type="text" id="x2" />
Y2<input type="text" id="y2" /><br />
link<input type="text" id="href" />
Alt<input type="text" id="alt" />
Shape<input type="text" id="alt" />
 _target_blank<input type="checkbox" id="alt" />
</div>

<%= render :partial => 'spree/admin/banners/list_pins' %>
<script type="text/javascript">
var click = 0;
$(document).ready(function() {
  $('img').click(function(e) {
    var offset = $("#bn_image").offset();
    
    if(click == 0){
    	$('#x1').val(e.pageX - offset.left);
    	$('#y1').val(e.pageY - offset.top);
    	 click = 1;
    }
    else{
    	$('#x2').val(e.pageX - offset.left);
    	$('#y2').val(e.pageY - offset.top);
    	 click = 0;
    }
   });
$('area').click(function(e) {
          $.ajax({
    type: "GET",
    url: "/admin/image_mappers/"+$(this).attr("id")+"/edit",
    success: function(data) {
         $("#edit_map").css('top',e.clientY );
         $("#edit_map").css('left',e.clientX);
         $("#edit_map").show();
         $("#edit_map").draggable();
    
  },
    error: function(data) {
          }
  });
         
 });

 


});

 $(document).on('click','.close_map_form',function(){
  $("#edit_map").hide();
 });
</script>

app/views/spree/admin/banners/search_paginate.js.erb
$('#show_banners').html('<%= escape_javascript render(:partial =>"spree/admin/banners/search_banners",:locals => { :banner => @banners}) %>');

$('#paginate').html('<%= escape_javascript(paginate(@banners, :remote => true).to_s) %>');

app/views/spree/admin/banners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Menu Name:</b>
  <%= @banner.name %>
</p>

<p>
  <b>URL:</b>
  <%= @banner.url %>
</p>

<p>
  <b>Image Name:</b>
  <%= "https://slider.styletagassets.com/banners/#{@banner.image_name}" %>
</p>

<p>
  <b>Sale:</b>
  <%= @banner.try(:active_sale_event).try(:eventable).try(:nil?) ? "No Sale Affiliated" : @banner.try(:active_sale_event).try(:eventable).try(:name) %>
</p>

<p>
  <b>Is Live?:</b>
  <%= @banner.live %>
</p>
<p>
  <b>Position:</b>
  <%= @banner.position %>
</p>
<p>
  <b>Type:</b>
  <%= @banner.banner_type %>
</p>


<%= link_to 'Edit', edit_admin_banner_path(@banner) %> |
<%= link_to 'Back', admin_banners_path %>